name: Java CI com Maven e Checkstyle

# O fluxo será disparado sempre que houver um push ou pull request na main
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual do GitHub
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instala o Java (JDK 17) para conseguir compilar o projeto
      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Executa o LINTING (Requisito do Barema - 5%)
      # Ele verifica se o seu código segue as boas práticas de escrita
      - name: Executar Análise Estática (Linting)
        run: mvn checkstyle:check

      # 4. Executa os TESTES AUTOMATIZADOS (Requisito do Barema - 10%)
      # Se algum teste falhar, a "bolinha" do GitHub fica vermelha
      - name: Executar Testes Automatizados
        run: mvn test

      # 5. Gera o arquivo final (.jar) para garantir que o projeto "builda"
      - name: Compilar Projeto (Build)
        run: mvn package -DskipTests